import { switchCase } from './util';

/**
 * Default key width in `px`.
 */
export const defaultWidth = 50;

/**
 * Retrieve the layout configurations.
 * @param {string} layoutId
 * @returns {object[]}
 */
export const getLayout = (layoutId) => {
  if (layouts.hasOwnProperty(layoutId)) {
    const layout = layouts[layoutId];
    return [
      ...layout.keycodes
        .map((row) => row.map((key) => ({
          ...keys.find((k) => k.name === key),
          width: switchCase(layout.widths)(1)(key) * defaultWidth,
        }))),
    ];
  }
}

/**
 * Keyboard layouts.
 */
export const layouts = {
  '60_ansi': {
    keycodes: [
      [ 'KEY_ESC', 'KEY_1', 'KEY_2', 'KEY_3', 'KEY_4', 'KEY_5', 'KEY_6', 'KEY_7', 'KEY_8', 'KEY_9', 'KEY_0', 'KEY_MINUS', 'KEY_EQUAL', 'KEY_BACKSPACE' ],
      [ 'KEY_TAB', 'KEY_Q', 'KEY_W', 'KEY_E', 'KEY_R', 'KEY_T', 'KEY_Y', 'KEY_U', 'KEY_I', 'KEY_O', 'KEY_P', 'KEY_LEFTBRACE', 'KEY_RIGHTBRACE', 'KEY_BACKSLASH' ],
      [ 'KEY_CAPSLOCK', 'KEY_A', 'KEY_S', 'KEY_D', 'KEY_F', 'KEY_G', 'KEY_H', 'KEY_J', 'KEY_K', 'KEY_L', 'KEY_SEMICOLON', 'KEY_APOSTROPHE', 'KEY_ENTER' ],
      [ 'KEY_LEFTSHIFT', 'KEY_Z', 'KEY_X', 'KEY_C', 'KEY_V', 'KEY_B', 'KEY_N', 'KEY_M', 'KEY_COMMA', 'KEY_DOT', 'KEY_SLASH', 'KEY_RIGHTSHIFT' ],
      [ 'KEY_LEFTCTRL', 'KEY_LEFTMETA', 'KEY_LEFTALT', 'KEY_SPACE', 'KEY_RIGHTALT', 'KEY_RIGHTMETA', 'KEY_COMPOSE', 'KEY_RIGHTCTRL' ],
    ],
    widths: {
      KEY_BACKSPACE: 1.75,
      KEY_TAB: 1.5,
      KEY_ENTER: 2.25,
      KEY_LEFTCTRL: 1.25,
      KEY_LEFTSHIFT: 2.5,
      KEY_BACKSLASH: 1.25,
      KEY_RIGHTSHIFT: 2.75,
      KEY_LEFTALT: 1.25,
      KEY_RIGHTALT: 1.25,
      KEY_SPACE: 7.75,
      KEY_CAPSLOCK: 1.75,
      KEY_RIGHTCTRL: 1.25,
      KEY_LEFTMETA: 1.25,
      KEY_RIGHTMETA: 1.25,
      KEY_COMPOSE: 1.25,
    },
  },
  'planck_mit': {
    keycodes: [
      [ 'KEY_ESC', 'KEY_Q', 'KEY_W', 'KEY_E', 'KEY_R', 'KEY_T', 'KEY_Y', 'KEY_U', 'KEY_I', 'KEY_O', 'KEY_P', 'KEY_BACKSPACE' ],
      [ 'KEY_TAB', 'KEY_A', 'KEY_S', 'KEY_D', 'KEY_F', 'KEY_G', 'KEY_H', 'KEY_J', 'KEY_K', 'KEY_L', 'KEY_SEMICOLON', 'KEY_APOSTROPHE' ],
      [ 'KEY_LEFTSHIFT', 'KEY_Z', 'KEY_X', 'KEY_C', 'KEY_V', 'KEY_B', 'KEY_N', 'KEY_M', 'KEY_COMMA', 'KEY_DOT', 'KEY_UP', 'KEY_ENTER' ],
      [ 'KEY_LEFTCTRL', 'KEY_LEFTMETA', 'KEY_CAPSLOCK', 'KEY_LEFTALT', 'KEY_LAYER', 'KEY_SPACE', 'KEY_LAYER', 'KEY_BACKSLASH', 'KEY_LEFT', 'KEY_DOWN', 'KEY_RIGHT' ],
    ],
    widths: {
      KEY_SPACE: 2.25,
    },
  },
};

/**
 * All of the available keys in `input-event-codes.h`.
 */
export const keys = [
  // ------ Custom layer key (keymap layers). ------
  { display: 'Layer', name: 'KEY_LAYER', code: -1 },
  // -----------------------------------------------
  { display: '', name: 'KEY_RESERVED', code: 0, },
  { display: 'Esc', name: 'KEY_ESC', code: 1, },
  { display: '!\n1', name: 'KEY_1', code: 2, },
  { display: '@\n2', name: 'KEY_2', code: 3, },
  { display: '#\n3', name: 'KEY_3', code: 4, },
  { display: '$\n4', name: 'KEY_4', code: 5, },
  { display: '%\n5', name: 'KEY_5', code: 6, },
  { display: '^\n6', name: 'KEY_6', code: 7, },
  { display: '&\n7', name: 'KEY_7', code: 8, },
  { display: '*\n8', name: 'KEY_8', code: 9, },
  { display: '(\n9', name: 'KEY_9', code: 10, },
  { display: ')\n0', name: 'KEY_0', code: 11, },
  { display: '-', name: 'KEY_MINUS', code: 12, },
  { display: '=', name: 'KEY_EQUAL', code: 13, },
  { display: 'Back Space', name: 'KEY_BACKSPACE', code: 14, },
  { display: 'Tab', name: 'KEY_TAB', code: 15, },
  { display: 'Q', name: 'KEY_Q', code: 16, },
  { display: 'W', name: 'KEY_W', code: 17, },
  { display: 'E', name: 'KEY_E', code: 18, },
  { display: 'R', name: 'KEY_R', code: 19, },
  { display: 'T', name: 'KEY_T', code: 20, },
  { display: 'Y', name: 'KEY_Y', code: 21, },
  { display: 'U', name: 'KEY_U', code: 22, },
  { display: 'I', name: 'KEY_I', code: 23, },
  { display: 'O', name: 'KEY_O', code: 24, },
  { display: 'P', name: 'KEY_P', code: 25, },
  { display: '{\n[', name: 'KEY_LEFTBRACE', code: 26, },
  { display: '}\n]', name: 'KEY_RIGHTBRACE', code: 27, },
  { display: 'Enter', name: 'KEY_ENTER', code: 28, },
  { display: 'Left Ctrl', name: 'KEY_LEFTCTRL', code: 29, },
  { display: 'A', name: 'KEY_A', code: 30, },
  { display: 'S', name: 'KEY_S', code: 31, },
  { display: 'D', name: 'KEY_D', code: 32, },
  { display: 'F', name: 'KEY_F', code: 33, },
  { display: 'G', name: 'KEY_G', code: 34, },
  { display: 'H', name: 'KEY_H', code: 35, },
  { display: 'J', name: 'KEY_J', code: 36, },
  { display: 'K', name: 'KEY_K', code: 37, },
  { display: 'L', name: 'KEY_L', code: 38, },
  { display: ':\n;', name: 'KEY_SEMICOLON', code: 39, },
  { display: '"\n\'', name: 'KEY_APOSTROPHE', code: 40, },
  { display: '~\n`', name: 'KEY_GRAVE', code: 41, },
  { display: 'Left Shift', name: 'KEY_LEFTSHIFT', code: 42, },
  { display: '|\n\\', name: 'KEY_BACKSLASH', code: 43, },
  { display: 'Z', name: 'KEY_Z', code: 44, },
  { display: 'X', name: 'KEY_X', code: 45, },
  { display: 'C', name: 'KEY_C', code: 46, },
  { display: 'V', name: 'KEY_V', code: 47, },
  { display: 'B', name: 'KEY_B', code: 48, },
  { display: 'N', name: 'KEY_N', code: 49, },
  { display: 'M', name: 'KEY_M', code: 50, },
  { display: '<\n,', name: 'KEY_COMMA', code: 51, },
  { display: '>\n.', name: 'KEY_DOT', code: 52, },
  { display: '?\n/', name: 'KEY_SLASH', code: 53, },
  { display: 'Right Shift', name: 'KEY_RIGHTSHIFT', code: 54, },
  { display: '', name: 'KEY_KPASTERISK', code: 55, },
  { display: 'Left Alt', name: 'KEY_LEFTALT', code: 56, },
  { display: 'Space', name: 'KEY_SPACE', code: 57, },
  { display: 'Caps Lock', name: 'KEY_CAPSLOCK', code: 58, },
  { display: 'F1', name: 'KEY_F1', code: 59, },
  { display: 'F2', name: 'KEY_F2', code: 60, },
  { display: 'F3', name: 'KEY_F3', code: 61, },
  { display: 'F4', name: 'KEY_F4', code: 62, },
  { display: 'F5', name: 'KEY_F5', code: 63, },
  { display: 'F6', name: 'KEY_F6', code: 64, },
  { display: 'F7', name: 'KEY_F7', code: 65, },
  { display: 'F8', name: 'KEY_F8', code: 66, },
  { display: 'F9', name: 'KEY_F9', code: 67, },
  { display: 'F10', name: 'KEY_F10', code: 68, },
  { display: 'Num Lock', name: 'KEY_NUMLOCK', code: 69, },
  { display: 'Scroll Lock', name: 'KEY_SCROLLLOCK', code: 70, },
  { display: '7', name: 'KEY_KP7', code: 71, },
  { display: '8', name: 'KEY_KP8', code: 72, },
  { display: '9', name: 'KEY_KP9', code: 73, },
  { display: '-', name: 'KEY_KPMINUS', code: 74, },
  { display: '4', name: 'KEY_KP4', code: 75, },
  { display: '5', name: 'KEY_KP5', code: 76, },
  { display: '6', name: 'KEY_KP6', code: 77, },
  { display: '+', name: 'KEY_KPPLUS', code: 78, },
  { display: '1', name: 'KEY_KP1', code: 79, },
  { display: '2', name: 'KEY_KP2', code: 80, },
  { display: '3', name: 'KEY_KP3', code: 81, },
  { display: '0', name: 'KEY_KP0', code: 82, },
  { display: '.', name: 'KEY_KPDOT', code: 83, },
  { display: '', name: 'KEY_ZENKAKUHANKAKU', code: 85, },
  { display: '', name: 'KEY_102ND', code: 86, },
  { display: 'F11', name: 'KEY_F11', code: 87, },
  { display: 'F12', name: 'KEY_F12', code: 88, },
  { display: '', name: 'KEY_RO', code: 89, },
  { display: '', name: 'KEY_KATAKANA', code: 90, },
  { display: '', name: 'KEY_HIRAGANA', code: 91, },
  { display: '', name: 'KEY_HENKAN', code: 92, },
  { display: '', name: 'KEY_KATAKANAHIRAGANA', code: 93, },
  { display: '', name: 'KEY_MUHENKAN', code: 94, },
  { display: '', name: 'KEY_KPJPCOMMA', code: 95, },
  { display: 'Enter', name: 'KEY_KPENTER', code: 96, },
  { display: 'Right Ctrl', name: 'KEY_RIGHTCTRL', code: 97, },
  { display: '/', name: 'KEY_KPSLASH', code: 98, },
  { display: '', name: 'KEY_SYSRQ', code: 99, },
  { display: 'Right Alt', name: 'KEY_RIGHTALT', code: 100, },
  { display: '', name: 'KEY_LINEFEED', code: 101, },
  { display: 'Home', name: 'KEY_HOME', code: 102, },
  { display: 'Up', name: 'KEY_UP', code: 103, },
  { display: 'Page Up', name: 'KEY_PAGEUP', code: 104, },
  { display: 'Left', name: 'KEY_LEFT', code: 105, },
  { display: 'Right', name: 'KEY_RIGHT', code: 106, },
  { display: 'End', name: 'KEY_END', code: 107, },
  { display: 'Down', name: 'KEY_DOWN', code: 108, },
  { display: 'Page Down', name: 'KEY_PAGEDOWN', code: 109, },
  { display: 'Insert', name: 'KEY_INSERT', code: 110, },
  { display: 'Delete', name: 'KEY_DELETE', code: 111, },
  { display: '', name: 'KEY_MACRO', code: 112, },
  { display: 'Mute', name: 'KEY_MUTE', code: 113, },
  { display: 'Volume Down', name: 'KEY_VOLUMEDOWN', code: 114, },
  { display: 'Volume Up', name: 'KEY_VOLUMEUP', code: 115, },
  { display: 'Power', name: 'KEY_POWER', code: 116, },
  { display: '', name: 'KEY_KPEQUAL', code: 117, },
  { display: '', name: 'KEY_KPPLUSMINUS', code: 118, },
  { display: 'Pause', name: 'KEY_PAUSE', code: 119, },
  { display: '', name: 'KEY_SCALE', code: 120, },
  { display: ',', name: 'KEY_KPCOMMA', code: 121, },
  { display: '', name: 'KEY_HANGEUL', code: 122, },
  { display: '', name: 'KEY_HANJA', code: 123, },
  { display: '', name: 'KEY_YEN', code: 124, },
  { display: 'Left OS', name: 'KEY_LEFTMETA', code: 125, },
  { display: 'Right OS', name: 'KEY_RIGHTMETA', code: 126, },
  { display: 'Menu', name: 'KEY_COMPOSE', code: 127, },
  { display: '', name: 'KEY_STOP', code: 128, },
  { display: '', name: 'KEY_AGAIN', code: 129, },
  { display: '', name: 'KEY_PROPS', code: 130, },
  { display: '', name: 'KEY_UNDO', code: 131, },
  { display: '', name: 'KEY_FRONT', code: 132, },
  { display: '', name: 'KEY_COPY', code: 133, },
  { display: '', name: 'KEY_OPEN', code: 134, },
  { display: '', name: 'KEY_PASTE', code: 135, },
  { display: '', name: 'KEY_FIND', code: 136, },
  { display: '', name: 'KEY_CUT', code: 137, },
  { display: '', name: 'KEY_HELP', code: 138, },
  { display: '', name: 'KEY_MENU', code: 139, },
  { display: '', name: 'KEY_CALC', code: 140, },
  { display: '', name: 'KEY_SETUP', code: 141, },
  { display: '', name: 'KEY_SLEEP', code: 142, },
  { display: '', name: 'KEY_WAKEUP', code: 143, },
  { display: '', name: 'KEY_FILE', code: 144, },
  { display: '', name: 'KEY_SENDFILE', code: 145, },
  { display: '', name: 'KEY_DELETEFILE', code: 146, },
  { display: '', name: 'KEY_XFER', code: 147, },
  { display: '', name: 'KEY_PROG1', code: 148, },
  { display: '', name: 'KEY_PROG2', code: 149, },
  { display: '', name: 'KEY_WWW', code: 150, },
  { display: '', name: 'KEY_MSDOS', code: 151, },
  { display: '', name: 'KEY_COFFEE', code: 152, },
  { display: '', name: 'KEY_ROTATE_DISPLAY', code: 153, },
  { display: '', name: 'KEY_CYCLEWINDOWS', code: 154, },
  { display: '', name: 'KEY_MAIL', code: 155, },
  { display: '', name: 'KEY_BOOKMARKS', code: 156, },
  { display: '', name: 'KEY_COMPUTER', code: 157, },
  { display: '', name: 'KEY_BACK', code: 158, },
  { display: '', name: 'KEY_FORWARD', code: 159, },
  { display: '', name: 'KEY_CLOSECD', code: 160, },
  { display: '', name: 'KEY_EJECTCD', code: 161, },
  { display: '', name: 'KEY_EJECTCLOSECD', code: 162, },
  { display: '', name: 'KEY_NEXTSONG', code: 163, },
  { display: '', name: 'KEY_PLAYPAUSE', code: 164, },
  { display: '', name: 'KEY_PREVIOUSSONG', code: 165, },
  { display: '', name: 'KEY_STOPCD', code: 166, },
  { display: '', name: 'KEY_RECORD', code: 167, },
  { display: '', name: 'KEY_REWIND', code: 168, },
  { display: '', name: 'KEY_PHONE', code: 169, },
  { display: '', name: 'KEY_ISO', code: 170, },
  { display: '', name: 'KEY_CONFIG', code: 171, },
  { display: '', name: 'KEY_HOMEPAGE', code: 172, },
  { display: '', name: 'KEY_REFRESH', code: 173, },
  { display: '', name: 'KEY_EXIT', code: 174, },
  { display: '', name: 'KEY_MOVE', code: 175, },
  { display: '', name: 'KEY_EDIT', code: 176, },
  { display: '', name: 'KEY_SCROLLUP', code: 177, },
  { display: '', name: 'KEY_SCROLLDOWN', code: 178, },
  { display: '', name: 'KEY_KPLEFTPAREN', code: 179, },
  { display: '', name: 'KEY_KPRIGHTPAREN', code: 180, },
  { display: '', name: 'KEY_NEW', code: 181, },
  { display: '', name: 'KEY_REDO', code: 182, },
  { display: '', name: 'KEY_F13', code: 183, },
  { display: '', name: 'KEY_F14', code: 184, },
  { display: '', name: 'KEY_F15', code: 185, },
  { display: '', name: 'KEY_F16', code: 186, },
  { display: '', name: 'KEY_F17', code: 187, },
  { display: '', name: 'KEY_F18', code: 188, },
  { display: '', name: 'KEY_F19', code: 189, },
  { display: '', name: 'KEY_F20', code: 190, },
  { display: '', name: 'KEY_F21', code: 191, },
  { display: '', name: 'KEY_F22', code: 192, },
  { display: '', name: 'KEY_F23', code: 193, },
  { display: '', name: 'KEY_F24', code: 194, },
  { display: '', name: 'KEY_PLAYCD', code: 200, },
  { display: '', name: 'KEY_PAUSECD', code: 201, },
  { display: '', name: 'KEY_PROG3', code: 202, },
  { display: '', name: 'KEY_PROG4', code: 203, },
  { display: '', name: 'KEY_DASHBOARD', code: 204, },
  { display: '', name: 'KEY_SUSPEND', code: 205, },
  { display: '', name: 'KEY_CLOSE', code: 206, },
  { display: '', name: 'KEY_PLAY', code: 207, },
  { display: '', name: 'KEY_FASTFORWARD', code: 208, },
  { display: '', name: 'KEY_BASSBOOST', code: 209, },
  { display: '', name: 'KEY_PRINT', code: 210, },
  { display: '', name: 'KEY_HP', code: 211, },
  { display: '', name: 'KEY_CAMERA', code: 212, },
  { display: '', name: 'KEY_SOUND', code: 213, },
  { display: '', name: 'KEY_QUESTION', code: 214, },
  { display: '', name: 'KEY_EMAIL', code: 215, },
  { display: '', name: 'KEY_CHAT', code: 216, },
  { display: '', name: 'KEY_SEARCH', code: 217, },
  { display: '', name: 'KEY_CONNECT', code: 218, },
  { display: '', name: 'KEY_FINANCE', code: 219, },
  { display: '', name: 'KEY_SPORT', code: 220, },
  { display: '', name: 'KEY_SHOP', code: 221, },
  { display: '', name: 'KEY_ALTERASE', code: 222, },
  { display: '', name: 'KEY_CANCEL', code: 223, },
  { display: '', name: 'KEY_BRIGHTNESSDOWN', code: 224, },
  { display: '', name: 'KEY_BRIGHTNESSUP', code: 225, },
  { display: '', name: 'KEY_MEDIA', code: 226, },
  { display: '', name: 'KEY_SWITCHVIDEOMODE', code: 227, },
  { display: '', name: 'KEY_KBDILLUMTOGGLE', code: 228, },
  { display: '', name: 'KEY_KBDILLUMDOWN', code: 229, },
  { display: '', name: 'KEY_KBDILLUMUP', code: 230, },
  { display: '', name: 'KEY_SEND', code: 231, },
  { display: '', name: 'KEY_REPLY', code: 232, },
  { display: '', name: 'KEY_FORWARDMAIL', code: 233, },
  { display: '', name: 'KEY_SAVE', code: 234, },
  { display: '', name: 'KEY_DOCUMENTS', code: 235, },
  { display: '', name: 'KEY_BATTERY', code: 236, },
  { display: '', name: 'KEY_BLUETOOTH', code: 237, },
  { display: '', name: 'KEY_WLAN', code: 238, },
  { display: '', name: 'KEY_UWB', code: 239, },
  { display: '', name: 'KEY_UNKNOWN', code: 240, },
  { display: '', name: 'KEY_VIDEO_NEXT', code: 241, },
  { display: '', name: 'KEY_VIDEO_PREV', code: 242, },
  { display: '', name: 'KEY_BRIGHTNESS_CYCLE', code: 243, },
  { display: '', name: 'KEY_BRIGHTNESS_AUTO', code: 244, },
  { display: '', name: 'KEY_DISPLAY_OFF', code: 245, },
  { display: '', name: 'KEY_WWAN', code: 246, },
  { display: '', name: 'KEY_RFKILL', code: 247, },
  { display: '', name: 'KEY_MICMUTE', code: 248, },
  { display: '', name: 'BTN_MISC', code: 0x100, },
  { display: '', name: 'BTN_0', code: 0x100, },
  { display: '', name: 'BTN_1', code: 0x101, },
  { display: '', name: 'BTN_2', code: 0x102, },
  { display: '', name: 'BTN_3', code: 0x103, },
  { display: '', name: 'BTN_4', code: 0x104, },
  { display: '', name: 'BTN_5', code: 0x105, },
  { display: '', name: 'BTN_6', code: 0x106, },
  { display: '', name: 'BTN_7', code: 0x107, },
  { display: '', name: 'BTN_8', code: 0x108, },
  { display: '', name: 'BTN_9', code: 0x109, },
  { display: '', name: 'BTN_MOUSE', code: 0x110, },
  { display: '', name: 'BTN_LEFT', code: 0x110, },
  { display: '', name: 'BTN_RIGHT', code: 0x111, },
  { display: '', name: 'BTN_MIDDLE', code: 0x112, },
  { display: '', name: 'BTN_SIDE', code: 0x113, },
  { display: '', name: 'BTN_EXTRA', code: 0x114, },
  { display: '', name: 'BTN_FORWARD', code: 0x115, },
  { display: '', name: 'BTN_BACK', code: 0x116, },
  { display: '', name: 'BTN_TASK', code: 0x117, },
  { display: '', name: 'BTN_JOYSTICK', code: 0x120, },
  { display: '', name: 'BTN_TRIGGER', code: 0x120, },
  { display: '', name: 'BTN_THUMB', code: 0x121, },
  { display: '', name: 'BTN_THUMB2', code: 0x122, },
  { display: '', name: 'BTN_TOP', code: 0x123, },
  { display: '', name: 'BTN_TOP2', code: 0x124, },
  { display: '', name: 'BTN_PINKIE', code: 0x125, },
  { display: '', name: 'BTN_BASE', code: 0x126, },
  { display: '', name: 'BTN_BASE2', code: 0x127, },
  { display: '', name: 'BTN_BASE3', code: 0x128, },
  { display: '', name: 'BTN_BASE4', code: 0x129, },
  { display: '', name: 'BTN_BASE5', code: 0x12a, },
  { display: '', name: 'BTN_BASE6', code: 0x12b, },
  { display: '', name: 'BTN_DEAD', code: 0x12f, },
  { display: '', name: 'BTN_GAMEPAD', code: 0x130, },
  { display: '', name: 'BTN_SOUTH', code: 0x130, },
  { display: '', name: 'BTN_EAST', code: 0x131, },
  { display: '', name: 'BTN_C', code: 0x132, },
  { display: '', name: 'BTN_NORTH', code: 0x133, },
  { display: '', name: 'BTN_WEST', code: 0x134, },
  { display: '', name: 'BTN_Z', code: 0x135, },
  { display: '', name: 'BTN_TL', code: 0x136, },
  { display: '', name: 'BTN_TR', code: 0x137, },
  { display: '', name: 'BTN_TL2', code: 0x138, },
  { display: '', name: 'BTN_TR2', code: 0x139, },
  { display: '', name: 'BTN_SELECT', code: 0x13a, },
  { display: '', name: 'BTN_START', code: 0x13b, },
  { display: '', name: 'BTN_MODE', code: 0x13c, },
  { display: '', name: 'BTN_THUMBL', code: 0x13d, },
  { display: '', name: 'BTN_THUMBR', code: 0x13e, },
  { display: '', name: 'BTN_DIGI', code: 0x140, },
  { display: '', name: 'BTN_TOOL_PEN', code: 0x140, },
  { display: '', name: 'BTN_TOOL_RUBBER', code: 0x141, },
  { display: '', name: 'BTN_TOOL_BRUSH', code: 0x142, },
  { display: '', name: 'BTN_TOOL_PENCIL', code: 0x143, },
  { display: '', name: 'BTN_TOOL_AIRBRUSH', code: 0x144, },
  { display: '', name: 'BTN_TOOL_FINGER', code: 0x145, },
  { display: '', name: 'BTN_TOOL_MOUSE', code: 0x146, },
  { display: '', name: 'BTN_TOOL_LENS', code: 0x147, },
  { display: '', name: 'BTN_TOOL_QUINTTAP', code: 0x148, },
  { display: '', name: 'BTN_STYLUS3', code: 0x149, },
  { display: '', name: 'BTN_TOUCH', code: 0x14a, },
  { display: '', name: 'BTN_STYLUS', code: 0x14b, },
  { display: '', name: 'BTN_STYLUS2', code: 0x14c, },
  { display: '', name: 'BTN_TOOL_DOUBLETAP', code: 0x14d, },
  { display: '', name: 'BTN_TOOL_TRIPLETAP', code: 0x14e, },
  { display: '', name: 'BTN_TOOL_QUADTAP', code: 0x14f, },
  { display: '', name: 'BTN_WHEEL', code: 0x150, },
  { display: '', name: 'BTN_GEAR_DOWN', code: 0x150, },
  { display: '', name: 'BTN_GEAR_UP', code: 0x151, },
  { display: '', name: 'KEY_OK', code: 0x160, },
  { display: '', name: 'KEY_SELECT', code: 0x161, },
  { display: '', name: 'KEY_GOTO', code: 0x162, },
  { display: '', name: 'KEY_CLEAR', code: 0x163, },
  { display: '', name: 'KEY_POWER2', code: 0x164, },
  { display: '', name: 'KEY_OPTION', code: 0x165, },
  { display: '', name: 'KEY_INFO', code: 0x166, },
  { display: '', name: 'KEY_TIME', code: 0x167, },
  { display: '', name: 'KEY_VENDOR', code: 0x168, },
  { display: '', name: 'KEY_ARCHIVE', code: 0x169, },
  { display: '', name: 'KEY_PROGRAM', code: 0x16a, },
  { display: '', name: 'KEY_CHANNEL', code: 0x16b, },
  { display: '', name: 'KEY_FAVORITES', code: 0x16c, },
  { display: '', name: 'KEY_EPG', code: 0x16d, },
  { display: '', name: 'KEY_PVR', code: 0x16e, },
  { display: '', name: 'KEY_MHP', code: 0x16f, },
  { display: '', name: 'KEY_LANGUAGE', code: 0x170, },
  { display: '', name: 'KEY_TITLE', code: 0x171, },
  { display: '', name: 'KEY_SUBTITLE', code: 0x172, },
  { display: '', name: 'KEY_ANGLE', code: 0x173, },
  { display: '', name: 'KEY_FULL_SCREEN', code: 0x174, },
  { display: '', name: 'KEY_MODE', code: 0x175, },
  { display: '', name: 'KEY_KEYBOARD', code: 0x176, },
  { display: '', name: 'KEY_ASPECT_RATIO', code: 0x177, },
  { display: '', name: 'KEY_PC', code: 0x178, },
  { display: '', name: 'KEY_TV', code: 0x179, },
  { display: '', name: 'KEY_TV2', code: 0x17a, },
  { display: '', name: 'KEY_VCR', code: 0x17b, },
  { display: '', name: 'KEY_VCR2', code: 0x17c, },
  { display: '', name: 'KEY_SAT', code: 0x17d, },
  { display: '', name: 'KEY_SAT2', code: 0x17e, },
  { display: '', name: 'KEY_CD', code: 0x17f, },
  { display: '', name: 'KEY_TAPE', code: 0x180, },
  { display: '', name: 'KEY_RADIO', code: 0x181, },
  { display: '', name: 'KEY_TUNER', code: 0x182, },
  { display: '', name: 'KEY_PLAYER', code: 0x183, },
  { display: '', name: 'KEY_TEXT', code: 0x184, },
  { display: '', name: 'KEY_DVD', code: 0x185, },
  { display: '', name: 'KEY_AUX', code: 0x186, },
  { display: '', name: 'KEY_MP3', code: 0x187, },
  { display: '', name: 'KEY_AUDIO', code: 0x188, },
  { display: '', name: 'KEY_VIDEO', code: 0x189, },
  { display: '', name: 'KEY_DIRECTORY', code: 0x18a, },
  { display: '', name: 'KEY_LIST', code: 0x18b, },
  { display: '', name: 'KEY_MEMO', code: 0x18c, },
  { display: '', name: 'KEY_CALENDAR', code: 0x18d, },
  { display: '', name: 'KEY_RED', code: 0x18e, },
  { display: '', name: 'KEY_GREEN', code: 0x18f, },
  { display: '', name: 'KEY_YELLOW', code: 0x190, },
  { display: '', name: 'KEY_BLUE', code: 0x191, },
  { display: '', name: 'KEY_CHANNELUP', code: 0x192, },
  { display: '', name: 'KEY_CHANNELDOWN', code: 0x193, },
  { display: '', name: 'KEY_FIRST', code: 0x194, },
  { display: '', name: 'KEY_LAST', code: 0x195, },
  { display: '', name: 'KEY_AB', code: 0x196, },
  { display: '', name: 'KEY_NEXT', code: 0x197, },
  { display: '', name: 'KEY_RESTART', code: 0x198, },
  { display: '', name: 'KEY_SLOW', code: 0x199, },
  { display: '', name: 'KEY_SHUFFLE', code: 0x19a, },
  { display: '', name: 'KEY_BREAK', code: 0x19b, },
  { display: '', name: 'KEY_PREVIOUS', code: 0x19c, },
  { display: '', name: 'KEY_DIGITS', code: 0x19d, },
  { display: '', name: 'KEY_TEEN', code: 0x19e, },
  { display: '', name: 'KEY_TWEN', code: 0x19f, },
  { display: '', name: 'KEY_VIDEOPHONE', code: 0x1a0, },
  { display: '', name: 'KEY_GAMES', code: 0x1a1, },
  { display: '', name: 'KEY_ZOOMIN', code: 0x1a2, },
  { display: '', name: 'KEY_ZOOMOUT', code: 0x1a3, },
  { display: '', name: 'KEY_ZOOMRESET', code: 0x1a4, },
  { display: '', name: 'KEY_WORDPROCESSOR', code: 0x1a5, },
  { display: '', name: 'KEY_EDITOR', code: 0x1a6, },
  { display: '', name: 'KEY_SPREADSHEET', code: 0x1a7, },
  { display: '', name: 'KEY_GRAPHICSEDITOR', code: 0x1a8, },
  { display: '', name: 'KEY_PRESENTATION', code: 0x1a9, },
  { display: '', name: 'KEY_DATABASE', code: 0x1aa, },
  { display: '', name: 'KEY_NEWS', code: 0x1ab, },
  { display: '', name: 'KEY_VOICEMAIL', code: 0x1ac, },
  { display: '', name: 'KEY_ADDRESSBOOK', code: 0x1ad, },
  { display: '', name: 'KEY_MESSENGER', code: 0x1ae, },
  { display: '', name: 'KEY_DISPLAYTOGGLE', code: 0x1af, },
  { display: '', name: 'KEY_SPELLCHECK', code: 0x1b0, },
  { display: '', name: 'KEY_LOGOFF', code: 0x1b1, },
  { display: '', name: 'KEY_DOLLAR', code: 0x1b2, },
  { display: '', name: 'KEY_EURO', code: 0x1b3, },
  { display: '', name: 'KEY_FRAMEBACK', code: 0x1b4, },
  { display: '', name: 'KEY_FRAMEFORWARD', code: 0x1b5, },
  { display: '', name: 'KEY_CONTEXT_MENU', code: 0x1b6, },
  { display: '', name: 'KEY_MEDIA_REPEAT', code: 0x1b7, },
  { display: '', name: 'KEY_10CHANNELSUP', code: 0x1b8, },
  { display: '', name: 'KEY_10CHANNELSDOWN', code: 0x1b9, },
  { display: '', name: 'KEY_IMAGES', code: 0x1ba, },
  { display: '', name: 'KEY_DEL_EOL', code: 0x1c0, },
  { display: '', name: 'KEY_DEL_EOS', code: 0x1c1, },
  { display: '', name: 'KEY_INS_LINE', code: 0x1c2, },
  { display: '', name: 'KEY_DEL_LINE', code: 0x1c3, },
  { display: '', name: 'KEY_FN', code: 0x1d0, },
  { display: '', name: 'KEY_FN_ESC', code: 0x1d1, },
  { display: '', name: 'KEY_FN_F1', code: 0x1d2, },
  { display: '', name: 'KEY_FN_F2', code: 0x1d3, },
  { display: '', name: 'KEY_FN_F3', code: 0x1d4, },
  { display: '', name: 'KEY_FN_F4', code: 0x1d5, },
  { display: '', name: 'KEY_FN_F5', code: 0x1d6, },
  { display: '', name: 'KEY_FN_F6', code: 0x1d7, },
  { display: '', name: 'KEY_FN_F7', code: 0x1d8, },
  { display: '', name: 'KEY_FN_F8', code: 0x1d9, },
  { display: '', name: 'KEY_FN_F9', code: 0x1da, },
  { display: '', name: 'KEY_FN_F10', code: 0x1db, },
  { display: '', name: 'KEY_FN_F11', code: 0x1dc, },
  { display: '', name: 'KEY_FN_F12', code: 0x1dd, },
  { display: '', name: 'KEY_FN_1', code: 0x1de, },
  { display: '', name: 'KEY_FN_2', code: 0x1df, },
  { display: '', name: 'KEY_FN_D', code: 0x1e0, },
  { display: '', name: 'KEY_FN_E', code: 0x1e1, },
  { display: '', name: 'KEY_FN_F', code: 0x1e2, },
  { display: '', name: 'KEY_FN_S', code: 0x1e3, },
  { display: '', name: 'KEY_FN_B', code: 0x1e4, },
  { display: '', name: 'KEY_BRL_DOT1', code: 0x1f1, },
  { display: '', name: 'KEY_BRL_DOT2', code: 0x1f2, },
  { display: '', name: 'KEY_BRL_DOT3', code: 0x1f3, },
  { display: '', name: 'KEY_BRL_DOT4', code: 0x1f4, },
  { display: '', name: 'KEY_BRL_DOT5', code: 0x1f5, },
  { display: '', name: 'KEY_BRL_DOT6', code: 0x1f6, },
  { display: '', name: 'KEY_BRL_DOT7', code: 0x1f7, },
  { display: '', name: 'KEY_BRL_DOT8', code: 0x1f8, },
  { display: '', name: 'KEY_BRL_DOT9', code: 0x1f9, },
  { display: '', name: 'KEY_BRL_DOT10', code: 0x1fa, },
  { display: '', name: 'KEY_NUMERIC_0', code: 0x200, },
  { display: '', name: 'KEY_NUMERIC_1', code: 0x201, },
  { display: '', name: 'KEY_NUMERIC_2', code: 0x202, },
  { display: '', name: 'KEY_NUMERIC_3', code: 0x203, },
  { display: '', name: 'KEY_NUMERIC_4', code: 0x204, },
  { display: '', name: 'KEY_NUMERIC_5', code: 0x205, },
  { display: '', name: 'KEY_NUMERIC_6', code: 0x206, },
  { display: '', name: 'KEY_NUMERIC_7', code: 0x207, },
  { display: '', name: 'KEY_NUMERIC_8', code: 0x208, },
  { display: '', name: 'KEY_NUMERIC_9', code: 0x209, },
  { display: '', name: 'KEY_NUMERIC_STAR', code: 0x20a, },
  { display: '', name: 'KEY_NUMERIC_POUND', code: 0x20b, },
  { display: '', name: 'KEY_NUMERIC_A', code: 0x20c, },
  { display: '', name: 'KEY_NUMERIC_B', code: 0x20d, },
  { display: '', name: 'KEY_NUMERIC_C', code: 0x20e, },
  { display: '', name: 'KEY_NUMERIC_D', code: 0x20f, },
  { display: '', name: 'KEY_CAMERA_FOCUS', code: 0x210, },
  { display: '', name: 'KEY_WPS_BUTTON', code: 0x211, },
  { display: '', name: 'KEY_TOUCHPAD_TOGGLE', code: 0x212, },
  { display: '', name: 'KEY_TOUCHPAD_ON', code: 0x213, },
  { display: '', name: 'KEY_TOUCHPAD_OFF', code: 0x214, },
  { display: '', name: 'KEY_CAMERA_ZOOMIN', code: 0x215, },
  { display: '', name: 'KEY_CAMERA_ZOOMOUT', code: 0x216, },
  { display: '', name: 'KEY_CAMERA_UP', code: 0x217, },
  { display: '', name: 'KEY_CAMERA_DOWN', code: 0x218, },
  { display: '', name: 'KEY_CAMERA_LEFT', code: 0x219, },
  { display: '', name: 'KEY_CAMERA_RIGHT', code: 0x21a, },
  { display: '', name: 'KEY_ATTENDANT_ON', code: 0x21b, },
  { display: '', name: 'KEY_ATTENDANT_OFF', code: 0x21c, },
  { display: '', name: 'KEY_ATTENDANT_TOGGLE', code: 0x21d, },
  { display: '', name: 'KEY_LIGHTS_TOGGLE', code: 0x21e, },
  { display: '', name: 'BTN_DPAD_UP', code: 0x220, },
  { display: '', name: 'BTN_DPAD_DOWN', code: 0x221, },
  { display: '', name: 'BTN_DPAD_LEFT', code: 0x222, },
  { display: '', name: 'BTN_DPAD_RIGHT', code: 0x223, },
  { display: '', name: 'KEY_ALS_TOGGLE', code: 0x230, },
  { display: '', name: 'KEY_ROTATE_LOCK_TOGGLE', code: 0x231, },
  { display: '', name: 'KEY_BUTTONCONFIG', code: 0x240, },
  { display: '', name: 'KEY_TASKMANAGER', code: 0x241, },
  { display: '', name: 'KEY_JOURNAL', code: 0x242, },
  { display: '', name: 'KEY_CONTROLPANEL', code: 0x243, },
  { display: '', name: 'KEY_APPSELECT', code: 0x244, },
  { display: '', name: 'KEY_SCREENSAVER', code: 0x245, },
  { display: '', name: 'KEY_VOICECOMMAND', code: 0x246, },
  { display: '', name: 'KEY_ASSISTANT', code: 0x247, },
  { display: '', name: 'KEY_KBD_LAYOUT_NEXT', code: 0x248, },
  { display: '', name: 'KEY_BRIGHTNESS_MIN', code: 0x250, },
  { display: '', name: 'KEY_BRIGHTNESS_MAX', code: 0x251, },
  { display: '', name: 'KEY_KBDINPUTASSIST_PREV', code: 0x260, },
  { display: '', name: 'KEY_KBDINPUTASSIST_NEXT', code: 0x261, },
  { display: '', name: 'KEY_KBDINPUTASSIST_PREVGROUP', code: 0x262, },
  { display: '', name: 'KEY_KBDINPUTASSIST_NEXTGROUP', code: 0x263, },
  { display: '', name: 'KEY_KBDINPUTASSIST_ACCEPT', code: 0x264, },
  { display: '', name: 'KEY_KBDINPUTASSIST_CANCEL', code: 0x265, },
  { display: '', name: 'KEY_RIGHT_UP', code: 0x266, },
  { display: '', name: 'KEY_RIGHT_DOWN', code: 0x267, },
  { display: '', name: 'KEY_LEFT_UP', code: 0x268, },
  { display: '', name: 'KEY_LEFT_DOWN', code: 0x269, },
  { display: '', name: 'KEY_ROOT_MENU', code: 0x26a, },
  { display: '', name: 'KEY_MEDIA_TOP_MENU', code: 0x26b, },
  { display: '', name: 'KEY_NUMERIC_11', code: 0x26c, },
  { display: '', name: 'KEY_NUMERIC_12', code: 0x26d, },
  { display: '', name: 'KEY_AUDIO_DESC', code: 0x26e, },
  { display: '', name: 'KEY_3D_MODE', code: 0x26f, },
  { display: '', name: 'KEY_NEXT_FAVORITE', code: 0x270, },
  { display: '', name: 'KEY_STOP_RECORD', code: 0x271, },
  { display: '', name: 'KEY_PAUSE_RECORD', code: 0x272, },
  { display: '', name: 'KEY_VOD', code: 0x273, },
  { display: '', name: 'KEY_UNMUTE', code: 0x274, },
  { display: '', name: 'KEY_FASTREVERSE', code: 0x275, },
  { display: '', name: 'KEY_SLOWREVERSE', code: 0x276, },
];
